/**
 * DarkForensicDossier — self-contained, presentation-only dark theme report.
 * Used at /dev/testing1. Does NOT replace TruthReportClassic.
 *
 * Pure UI. No hooks beyond local state. No data fetching. No edge function calls.
 */

import { ExecutiveSummary } from "./sections/ExecutiveSummary";
import { TopForensicFindings } from "./sections/TopForensicFindings";
import { PropertyProfile } from "./sections/PropertyProfile";
import { ProjectScope } from "./sections/ProjectScope";
import { ProductEngineering } from "./sections/ProductEngineering";
import { Compliance } from "./sections/Compliance";
import { FinancialIntegrity } from "./sections/FinancialIntegrity";
import { ForensicVulnerabilities } from "./sections/ForensicVulnerabilities";
import type { DossierFixture } from "./fixtures";

export interface DarkForensicDossierProps {
  data: DossierFixture;
  accessLevel: "preview" | "full";
}

export function DarkForensicDossier({ data, accessLevel }: DarkForensicDossierProps) {
  const locked = accessLevel === "preview";

  return (
    <div className="min-h-screen bg-gradient-to-b from-dossier-surface to-dossier-elevated">
      <div className="max-w-5xl mx-auto px-4 md:px-6 py-8 md:py-12 space-y-6">
        <header className="mb-2">
          <h1 className="text-2xl md:text-3xl font-bold text-white">
            Forensic Quote Dossier
          </h1>
          <p className="text-sm text-dossier-txt-secondary mt-1">
            Generated by WindowMan Scanner Brain · 37-signal forensic analysis
          </p>
        </header>

        {/* Section 1 — always visible */}
        <ExecutiveSummary
          grade={data.grade}
          signalsExtracted={data.signalsExtracted}
          signalsTotal={data.signalsTotal}
          criticalFlags={data.criticalFlags}
          confidencePct={data.confidencePct}
          verdict={data.verdict}
        />

        {/* Section 2 — visible but blurred in preview */}
        <TopForensicFindings findings={data.topFindings} locked={locked} />

        {/* Section 3 — always visible */}
        <PropertyProfile data={data} />

        {/* Sections 4-8 — full only */}
        {!locked && (
          <>
            <ProjectScope data={data} />
            <ProductEngineering data={data} />
            <Compliance data={data} />
            <FinancialIntegrity data={data} />
            <ForensicVulnerabilities vulnerabilities={data.vulnerabilities} />
          </>
        )}
      </div>
    </div>
  );
}
