export const ADMIN_DASHBOARD_TABS = [
  "mission-control",
  "surface-map",
  "prioritization",
  "launch",
  "command",
  "routing",
  "lead-assignments",
  "lead-release",
  "syndicate-health",
  "contractor-performance",
  "pipeline",
  "ghosts",
  "needs-review",
  "engine",
  "contractors",
  "onboarding",
  "outcomes",
  "reporting",
  "lifecycle",
  "feedback",
  "shared-market",
  "report-prep",
  "audit",
  "readiness",
  "training",
  "rollout",
  "data-quality",
  "exceptions",
  "docs",
  "learnings",
  "change-mgmt",
  "governance",
  "drills",
  "expansion",
  "tech-debt",
  "consistency",
  "attribution",
  "signal-dispatch",
  "revenue-dispatch-readiness",
  "revenue-dry-run",
  "client-platform-configs",
  "dispatch-dry-run",
  "dispatch-outbox",
  "dispatch-attempts",
  "dispatch-governance",
  "pilot",
  "delivery-inspector",
  "outcome-inspector",
  "session-diag",
  "otp-ops",
] as const;

export type AdminDashboardTab = (typeof ADMIN_DASHBOARD_TABS)[number];

const ADMIN_DASHBOARD_TAB_SET = new Set<string>(ADMIN_DASHBOARD_TABS);

export const PUBLIC_ROOT_ROUTE_DENYLIST = new Set([
  "about",
  "contact",
  "faq",
  "privacy",
  "terms",
  "disclaimer",
  "how-we-beat-window-quotes",
  "contractors",
  "contractors2",
  "contractors3",
  "estimate",
  "diagnosis",
  "lp",
  "partner",
  "report",
  "admin",
  "demo-classic",
  "dev",
  "devtesting",
]);

export function isAdminDashboardTab(value: string): value is AdminDashboardTab {
  return ADMIN_DASHBOARD_TAB_SET.has(value);
}