import { Info } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { formatPerformanceRate, type ContractorPerformanceSummary } from "@/services/contractorPerformance";

function Kpi({ label, value, definition }: { label: string; value: string | number; definition: string }) {
  return <div className="rounded-lg border border-slate-300 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="text-xs font-extrabold uppercase tracking-wide text-slate-600">{label}</p><Tooltip><TooltipTrigger asChild><button type="button" className="rounded-full text-slate-500 transition hover:text-slate-950 focus:outline-none focus:ring-2 focus:ring-slate-400" aria-label={`${label} definition`}><Info className="h-4 w-4" aria-hidden /></button></TooltipTrigger><TooltipContent className="max-w-xs text-xs font-semibold leading-5"><p>{definition}</p></TooltipContent></Tooltip></div><p className="mt-2 text-2xl font-black tracking-tight text-slate-950">{value}</p></div>;
}

function formatLastActivity(value: string | null): string {
  return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(value)) : "—";
}

export function ContractorPerformanceKpiStrip({ summaries }: { summaries: ContractorPerformanceSummary[] }) {
  const totals = summaries.reduce((acc, row) => ({ assigned: acc.assigned + row.assignedCount, released: acc.released + row.releasedCount, contacted: acc.contacted + row.contactedCount, scheduled: acc.scheduled + row.scheduledCount, proposalDelivered: acc.proposalDelivered + row.quoteDeliveredCount, sold: acc.sold + row.soldCount, lost: acc.lost + row.lostCount }), { assigned: 0, released: 0, contacted: 0, scheduled: 0, proposalDelivered: 0, sold: 0, lost: 0 });
  const avgCloseRate = totals.released > 0 ? totals.sold / totals.released : null;
  const sortedActivityDates = summaries.map((row) => row.lastActivityAt).filter(Boolean).sort();
  const lastActivityAt = sortedActivityDates.length ? sortedActivityDates[sortedActivityDates.length - 1] : null;
  return <TooltipProvider delayDuration={150}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-9"><Kpi label="Assigned" value={totals.assigned} definition="All contractor lead assignments created in the selected window, before release approval or contractor outcome updates." /><Kpi label="Released" value={totals.released} definition="Assignments whose contact release was approved in the selected window. This is the denominator for contact, appointment, proposal, close, and loss rates." /><Kpi label="Contacted" value={totals.contacted} definition="Released opportunities with an outcome state of contacted or a later qualified state, including scheduled, proposal delivered, sold, or lost after contact." /><Kpi label="Scheduled" value={totals.scheduled} definition="Released opportunities that reached a scheduled appointment / meeting-scheduled outcome state." /><Kpi label="Proposal delivered" value={totals.proposalDelivered} definition="Released opportunities where the contractor submitted a quote-delivered or proposal-delivered outcome state." /><Kpi label="Sold" value={totals.sold} definition="Released opportunities with a validated sold-closed outcome. Estimated revenue is not counted as sold unless the sold outcome is present." /><Kpi label="Lost" value={totals.lost} definition="Released opportunities with a lost outcome state, including customer-lost, contractor-declined, or no-sale classifications captured by the outcome flow." /><Kpi label="Close rate" value={formatPerformanceRate(avgCloseRate)} definition="Sold divided by released opportunities for the selected window: sold_closed count ÷ released count." /><Kpi label="Last activity" value={formatLastActivity(lastActivityAt)} definition="Most recent aggregate assignment, release, or contractor outcome activity timestamp found for the filtered contractors." /></div></TooltipProvider>;
}
