import type { InsightDefinition } from "./types";

export const INTELLIGENCE_INSIGHTS: readonly InsightDefinition[] = [
  { id: "quoted_vs_accepted_price", number: 1, title: "Quoted price versus verified accepted price", publicTitle: "What homeowners are quoted vs what buyers accept", question: "How does the offered price compare with the price buyers verify they accepted?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "acceptance_by_price_position", number: 2, title: "Acceptance by quoted-price position", publicTitle: "Where accepted projects sit in the observed range", question: "Where do accepted projects fall within the observed quoted-price distribution?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "initial_to_accepted_delta", number: 3, title: "Initial estimate to accepted revision", publicTitle: "How quotes change before signing", question: "How much does price and scope move between the first offer and accepted revision?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "accepted_to_final_delta", number: 4, title: "Accepted contract to final outcome", publicTitle: "How final costs differ from signed price", question: "How much does the accepted contract change by installation or final invoice?", maturity: "M3", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "price_per_opening", number: 5, title: "Price per physical opening", publicTitle: "Observed price per physical opening", question: "How do quoted and accepted prices compare under the approved opening definition?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "size_adjusted_price", number: 6, title: "Size-adjusted purchase price", publicTitle: "How size and configuration affect price", question: "How does accepted price change after controlling for approved size measures?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "product_tier_migration", number: 7, title: "Product tier migration", publicTitle: "What product types buyers actually choose", question: "Which products are offered and which products appear in the accepted revision?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "glass_package_premium", number: 8, title: "Glass and package premium", publicTitle: "What upgraded glass tends to add", question: "How do glass packages change observed accepted price and take rate?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "scope_completeness", number: 9, title: "Scope completeness", publicTitle: "What complete estimates usually spell out", question: "How does deterministic scope completeness relate to verified acceptance?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "payment_structure", number: 10, title: "Deposit, payment, and financing structure", publicTitle: "Common payment structures in accepted projects", question: "Which payment structures appear in quoted and verified accepted populations?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "warranty_specificity", number: 11, title: "Warranty specificity", publicTitle: "What buyers see in stronger warranties", question: "How does explicit product and labor warranty evidence vary across outcomes?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "quote_clarity", number: 12, title: "Quote clarity and later changes", publicTitle: "A quote-readiness checklist", question: "Do clearer estimates require fewer revisions and later changes?", maturity: "M3", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "multi_bid_spread", number: 13, title: "Multi-bid spread and winning position", publicTitle: "Does the lowest quote usually win?", question: "Where does the selected bid sit within the same verified project?", maturity: "M2", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
  { id: "contractor_discipline", number: 14, title: "Contractor pricing discipline", publicTitle: "Market-level pricing patterns", question: "How consistently do contractor offers, revisions, and final outcomes align?", maturity: "M3", audiences: ["FOUNDER"] },
  { id: "market_movement", number: 15, title: "Market movement over time and geography", publicTitle: "Your local market pulse", question: "How do quoted and verified accepted populations move across time and place?", maturity: "M4", audiences: ["FOUNDER", "SALES", "PUBLIC"] },
] as const;

export const INSIGHT_BY_ID = new Map(INTELLIGENCE_INSIGHTS.map((insight) => [insight.id, insight]));
