import type { QuoteMathLedgerProps } from "./QuoteMathLedger.types";

export const LEDGER_FIXTURE_FULL_DETECTION: QuoteMathLedgerProps = {
  contractorName: "Hurricane Shield Windows",
  totalQuotedPrice: 38_400,
  openingCount: 4,
  confidenceScore: 0.94,
  lineItems: [
    {
      description: "Impact Single-Hung Window 36x60",
      quantity: 2,
      unit_price: 1850,
      total_price: 3700,
      brand: "PGT",
      series: "WinGuard",
      dp_rating: "DP-50",
      noa_number: "FL-12345",
      dimensions: "36 x 60",
      opening_location: "Master Bedroom",
      opening_tag: "MB-1",
      product_assignment_text: "Single-hung impact window",
      glass_package_text: "Insulated laminated, Low-E, argon",
      glass_makeup_type: "insulated_laminated",
      glass_low_e_present: true,
      glass_argon_present: true,
      glass_spec_complete: true,
    },
    {
      description: "Impact Horizontal Roller 48x36",
      quantity: 1,
      unit_price: 2100,
      total_price: 2100,
      brand: "PGT",
      series: "WinGuard",
      dp_rating: "DP-45",
      noa_number: "FL-12346",
      dimensions: "48 x 36",
      opening_location: "Living Room",
      opening_tag: "LR-2",
      product_assignment_text: "Horizontal roller",
      glass_package_text: "Laminated, Low-E",
      glass_makeup_type: "laminated",
      glass_low_e_present: true,
      glass_argon_present: false,
      glass_spec_complete: true,
    },
    {
      description: "Impact Entry Door 36x80",
      quantity: 1,
      unit_price: 4200,
      total_price: 4200,
      brand: "Therma-Tru",
      series: "Pulse",
      dp_rating: "DP-50",
      noa_number: "FL-98765",
      dimensions: "36 x 80",
      opening_location: "Front Entry",
      opening_tag: "FE-1",
      product_assignment_text: "Full-lite impact entry door",
      glass_package_text: "Laminated sidelite glass",
      glass_makeup_type: "laminated",
      glass_spec_complete: true,
    },
    {
      description: "Installation labor — all openings",
      quantity: 4,
      unit_price: 7500,
      total_price: 30_000,
      brand: "Hurricane Shield Windows",
      series: "Standard install package",
      dp_rating: "DP-50",
      noa_number: "FL-INSTALL-01",
      dimensions: "—",
      opening_location: "Whole home",
      glass_package_text: "Per opening schedule",
      glass_spec_complete: true,
    },
  ],
};

export const LEDGER_FIXTURE_PARTIAL_DETECTION: QuoteMathLedgerProps = {
  contractorName: "Sunshine Impact Windows",
  totalQuotedPrice: 26_750,
  openingCount: 5,
  confidenceScore: 0.78,
  lineItems: [
    {
      description:
        "Custom oversized impact picture window with structural reinforcement and extended lead time per manufacturer schedule sheet attachment reference line A-12 through A-14",
      quantity: 1,
      unit_price: 4800,
      total_price: 4800,
      brand: "CGI",
      series: "Sentinel",
      dp_rating: "DP-55",
      noa_number: "FL-44001",
      dimensions: "96 x 72",
      opening_location: "Great Room",
      glass_package_text: "Insulated laminated",
      glass_spec_complete: true,
    },
    {
      description: "Impact casement window 24x48",
      quantity: 2,
      unit_price: 1425,
      total_price: 2850,
      brand: "CGI",
      series: "Sentinel",
      dimensions: "24 x 48",
      opening_location: "Bedroom 2",
      glass_package_text: "Laminated",
      glass_spec_complete: false,
    },
    {
      description: "Sliding glass door 72x80",
      quantity: 1,
      unit_price: 6200,
      total_price: 6200,
      series: "Commercial line",
      noa_number: "FL-22010",
      dimensions: "72 x 80",
      opening_location: "Rear patio",
      glass_package_text: "Not specified on line",
      glass_spec_complete: false,
    },
    {
      description: "Miscellaneous hardware allowance",
      quantity: 0,
      unit_price: null,
      total_price: null,
      opening_location: "Various",
    },
    {
      description: "Permit coordination fee",
      quantity: 1,
      unit_price: 450,
      total_price: 450,
      product_assignment_text: "Permit pull — responsibility not shown in parsed quote",
    },
  ],
};

export const LEDGER_FIXTURE_EMPTY: QuoteMathLedgerProps = {
  lineItems: [],
  contractorName: null,
  totalQuotedPrice: null,
  openingCount: null,
  confidenceScore: null,
};
