/**
 * Deterministic CTA copy — NOT generated by Gemini.
 *
 * Source-of-truth survey (Pass 1, read-only):
 * - RevealDiagnosisBridgeCard primary button: "A Better Quote is Moments Away"
 * - NextActionCard primary default: "Get a Better Quote Plan"
 * - Operator candidate: "If you'd like a reliable partner to offer you a better estimate, click below."
 *
 * Recommendation: reuse existing product CTA surfaces at render time; do not introduce
 * a third canonical string until Pass 2+ wires summary → ExecutiveSummaryBand.
 */
export const SUMMARY_OPERATOR_CTA_CANDIDATE =
  "If you'd like a reliable partner to offer you a better estimate, click below.";

export const EXISTING_REVEAL_DIAGNOSIS_BRIDGE_CTA =
  "A Better Quote is Moments Away";

export const EXISTING_NEXT_ACTION_CARD_CTA = "Get a Better Quote Plan";
