import { Info } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { formatPerformanceCurrency, formatPerformanceRate, type ContractorPerformanceSummary } from "@/services/contractorPerformance";

function Kpi({ label, value, definition }: { label: string; value: string | number; definition: string }) {
  return <div className="rounded-lg border border-slate-300 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="text-xs font-extrabold uppercase tracking-wide text-slate-600">{label}</p><Tooltip><TooltipTrigger asChild><button type="button" className="rounded-full text-slate-500 transition hover:text-slate-950 focus:outline-none focus:ring-2 focus:ring-slate-400" aria-label={`${label} definition`}><Info className="h-4 w-4" aria-hidden /></button></TooltipTrigger><TooltipContent className="max-w-xs text-xs font-semibold leading-5"><p>{definition}</p></TooltipContent></Tooltip></div><p className="mt-2 text-2xl font-black tracking-tight text-slate-950">{value}</p></div>;
}

function formatHours(value: number | null): string {
  if (value == null || Number.isNaN(value)) return "—";
  if (value < 1) return "<1h";
  return `${Math.round(value)}h`;
}

export function ContractorSelfPerformanceKpis({ summary }: { summary: ContractorPerformanceSummary }) {
  return <TooltipProvider delayDuration={150}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Kpi label="Assigned" value={summary.assignedCount} definition="All opportunities assigned to your contractor account in the selected window, before contact release or outcome progress." /><Kpi label="Released" value={summary.releasedCount} definition="Assigned opportunities where WindowMan approved contact release. Released count is the denominator for your contact, proposal, close, and loss rates." /><Kpi label="Attempting contact" value={summary.attemptingContactCount} definition="Released opportunities currently in the attempting-contact outcome state and not yet progressed to contacted, scheduled, proposal delivered, sold, or lost." /><Kpi label="Contacted" value={summary.contactedCount} definition="Released opportunities with contacted or a later qualified state, including scheduled, proposal delivered, sold, or lost after contact." /><Kpi label="Contact rate" value={formatPerformanceRate(summary.contactRate)} definition="Contacted divided by released opportunities: contacted count ÷ released count." /><Kpi label="Avg first update" value={formatHours(summary.averageTimeToFirstUpdateHours)} definition="Average hours from approved contact release to your first contractor outcome update for released opportunities with at least one update." /><Kpi label="Scheduled" value={summary.scheduledCount} definition="Released opportunities that reached a scheduled appointment / meeting-scheduled outcome state." /><Kpi label="Proposal delivered" value={summary.quoteDeliveredCount} definition="Released opportunities where a quote-delivered or proposal-delivered outcome was submitted." /><Kpi label="Sold" value={summary.soldCount} definition="Released opportunities with a validated sold-closed outcome state." /><Kpi label="Lost" value={summary.lostCount} definition="Released opportunities with a lost outcome state, including customer-lost, contractor-declined, or no-sale classifications captured by the outcome flow." /><Kpi label="Close rate" value={formatPerformanceRate(summary.closeRate)} definition="Sold divided by released opportunities: sold_closed count ÷ released count." /><Kpi label="Sold value" value={formatPerformanceCurrency(summary.soldValueCents)} definition="Total validated revenue from sold-closed outcomes only. Estimated values are not included unless the opportunity is marked sold." /></div></TooltipProvider>;
}
